### ISSUE TITLE
Use cluster-capacity programatically

### ISSUE THREAD

**Issue by povils** [kubernetes-sigs/cluster-capacity#119]
Is there a way how we could easily use this tool programatically?(It would probably require to migrate to go modules.)

Use case:
Create a single binary library which would call cluster-capacity programatically and do some actions based on the output

**Comment by ingvagabund** [comment]
Hey @povils, I wish I could be more helpful in this direction. As long as the scheduler framework [1] lives under k8s/kubernetes project [2] and does not have its own repo, all consumers of cluster capacity need to use anything but go modules. The main k8s/kubernetes project is not meant to be consumed directly. Which since go modules is enforced. Thus, the reason cluster capacity still relies on dep [3].

Going to your use case, I am +100 for any improvements or suggestions towards making the code consumable as a library. Is there any particular piece missing which you would like to have?

[1] https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md
[2] https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/framework
[3] https://github.com/golang/dep

**Comment by ingvagabund** [comment]
Just migrated to go modules: https://github.com/kubernetes-sigs/cluster-capacity/pull/140
